### ISSUE TITLE
version 2022.1 (release date 3.24、5.19)， Dll is not supported

### ISSUE THREAD

**Issue by Charltsing** [Plot1337/EazTrialRemover#1] opened 2022-08-12 04:54 UTC
Official version 2022.1 (release date is 5.19) is not supported

https://www.gapotchenko.com/eazfuscator.net/download 
Eazfuscator.NET.exe  2022.5.19 3:32

**Comment by ldstr** [comment] 2022-08-12 11:40
I tested it with the latest version of Eaz, and it worked as expected. Perhaps the tool didn't work due to an issue from your end? Did the tool throw any error(s)?

**Comment by ldstr** [comment] 2022-08-12 11:41
Please ignore that; I accidentally closed it haha

**Comment by Charltsing** [comment] 2022-08-23 13:50
sorry，i test dll，it not support。

after 7 days，my program report Error: module...

maybe EazTrialRemover can not support dll.

i try EAZ 3.24  and  5.19

**Comment by ldstr** [comment] 2022-08-26 11:46
Thanks for reporting! I'll look into that soon.

**Comment by 3dsbros64** [comment] 2022-09-04 00:13
@Plot1337 any updates?

**Comment by LordEliasTM** [comment] 2022-10-02 17:03
Hi, having the same problem with dlls.
The obfuscated dll is .NET 6.0
Output of the trial remover is:
```
Found: 0x02000009
Patched!
Saved!
Press any key to exit...
```
When i run the normal expired dll (without using the remover) it gives me this error:
```
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'value')
   at System.IO.UnmanagedMemoryStream.set_Position(Int64 value)
   at ☻♣.☻(Int32 ☻, Boolean ♥)
   at ☻♣.☻(Int32 ☻)
   at♥.☻()
   at ♠☻.☻(String[] ☻)
 ```
Though when i run the dll with trail removed even when it's not yet expired i get this error:
```
Unhandled exception. System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at ☻♣.♥.☻()
   at ☻♣.♥.☻(Int32 ☻)
   at ☻♣.♥.☻()
   at ☻♣.☻(Int32 ☻, Boolean ♥)
   at ☻♣.☻(Int32 ☻)
   at♥.☻()
   at ♠☻.☻(String[] ☻)
```
I hope this gives you enough information to attempt to fix it ; )

**Comment by LordEliasTM** [comment] 2022-10-02 18:26
I think i know where the problem lies.
Eaz now kinda checks the assembly metadata and stuff, so even if you just rename a method or class with dnSpy it will throw the second error mentioned above

**Comment by LordEliasTM** [comment] 2022-10-02 18:49
Would be really nice if you could share the installer of your eazfuscator 2022.1 versions, because they might've added it in a version after you downloaded it :)

**Comment by LordEliasTM** [comment] 2022-10-02 20:55
Okay so another update on my research.
On the official Eazfuscator website you need a valid license key in order to download older versions of their program, so i dug a bit to find places where old installers or binaries might be hosted, when i stumbled upon the [NuGet Gallery of Eazfuscator](https://www.nuget.org/packages/Gapotchenko.Eazfuscator.NET/).
Luckily the old versions of the packages hold the binaries too! You can get them if you download the package, extract it with i.e. 7-zip and open the 'tools' folder.
So i just installed the most recent version of Eazfuscator and replaced the files in the installation folder with the files from the old package.
Though then arose the next problem when building the project with Eazfuscator: "Method not found [...] Microsoft.IO.Path.GetFileName()...". This is caused by a recent update of MSBuild mentioned in this stackoverflow answer [](https://stackoverflow.com/a/73422940)
The only solution would be to downgrade the visual studio 2022 version to 17.0, though Microsoft only offers old downloads for Visual Studio Professional and Enterprise :/
If you want to work with .NET versions below 6.0 you are in luck, because visual studio 2019 supports them (which also has the old MSBuild version).
EDIT: you can just download the Nuget package in visual studio (2019) directly, I tested 2022.1.493, which worked just fine with Trail removing

**Comment by 3dsbros64** [comment] 2022-10-09 23:45
@LordEliasTM Just patch the time verification manually with DnSpy. Takes 1 minute and you will be able to use Eaz for exe and dlls. Yet you should not use Eazfuscator alone to obfuscate your applications.

My discord: 3dsbros64#0001

**Comment by ldstr** [comment] 2022-10-10 03:04
@LordEliasTM Are you sure your assembly wasn't protected with `PEVerify`?

**Comment by ldstr** [comment] 2022-10-10 06:36
Update: the issue is fixed! Please use the latest version of this tool: https://github.com/Plot1337/EazTrialRemover/releases/tag/1.1.0.0

DLLs are supported now; once again, please don't use `PEVeirfy`

**Closed as completed by ldstr** 2022-10-10 06:36 UTC
